{{- range .Values.deployment }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: {{ .name }}
 name: {{ .name }}
spec:
  volumes:
    - name: index-html
        configMap:
          name: '{{ .Chart.Name }}-html'
          defaultMode: 420
 replicas: 1
 selector:
   matchLabels:
     app: {{ .name }}
 strategy: {}
 template:
   metadata:
     labels:
       app: {{ .name }}
   spec:
     containers:
       volumeMounts:
         - name: index-html
           mountPath: /tmp/html # this will mount the html.index file to it application location
     - image: quay.io/rhdevelopers/bgd:1.0.0
       name: {{ .name }}
       env:
       - name: COLOR
         value: {{ .color }}
       resources: {}
       securityContext:
         allowPrivilegeEscalation: false
         capabilities:
           drop:
           - ALL
     securityContext:
       runAsNonRoot: true
       seccompProfile:
         type: RuntimeDefault
{{- end }}